image: python:3.8

clone:
  depth: full

definitions:
  steps:
    - step: &Test-run
        name: Run tests
        caches:
          - pip
        script:
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - pip install pytest
          - pytest -v lobpy/test/* --junitxml=test-reports/report.xml
    - step: &Pylint
        name: Lint Code
        script:
          # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
          - pip install flake8
          - flake8 . --extend-exclude=dist,build --show-source --statistics
    - step: &Github-sync
        name: Sync protected BitBucket repo with GitHub
        script:
          - git push --mirror git@github.com:shashwat1e4/lobpy.git


pipelines:
  default:
#    - parallel:
#      - step: *Test-run
#      - step: *Pylint
  branches:
    master:
      - step: *Github-sync